apps/comentario/urls.py
from django.urls import path
from .views import DetallePublicacionView, EditarComentarioView, EliminarComentarioView


app_name = 'comentario'
urlpatterns = [
    path('publicacion/<int:pk>/',DetallePublicacionView.as_view(), name='detalle_publicacion'),
    path('comentario/editar/<int:pk>/', EditarComentarioView.as_view(), name='editar_comentario'),
    path('comentario/eliminar_comentario/<int:pk>/', EliminarComentarioView.as_view(), name='eliminar_comentario'),
    ]

apps/publicacion/urls.py
from django.urls import path
from .views import CrearPublicacionView, DetallePublicacionView,  EditarPublicacionView,  ListaPublicacionesView, BorrarPublicacionView
from .views import EditarCategoriaView, EliminarCategoriaView, ListaCategoriasView, ListaPublicacionesPorCategoriaView, CrearCategoriaView, DetallePublicacionView

urlpatterns = [
    path('crear/', CrearPublicacionView.as_view(), name='crear_publicacion'),
    path('lista/', ListaPublicacionesView.as_view(), name='lista_publicaciones'),
    path('publicacion/<int:pk>/', DetallePublicacionView.as_view(), name='detalle_publicacion'), 
    path('publicacion/<int:pk>/editar/', EditarPublicacionView.as_view(), name='editar_publicacion'),
    path('publicacion/<int:pk>/eliminar/', BorrarPublicacionView.as_view(), name='eliminar_publicacion'),
    path('publicaciones/categoria/<int:categoria_id>/', ListaPublicacionesPorCategoriaView.as_view(), name='lista_publicaciones_categoria'),
    path('categoria/nueva/', CrearCategoriaView.as_view(), name='crear_categoria'),
    path('categorias/', ListaCategoriasView.as_view(), name='lista_categorias'),
    path('categoria/editar/<int:pk>/', EditarCategoriaView.as_view(), name='editar_categoria'),
    path('categoria/eliminar/<int:pk>/', EliminarCategoriaView.as_view(), name='eliminar_categoria'),
    ]

proyBlog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import NosotrosView
from .viewsC import contactanosView
from . import views

urlpatterns = [
    path('adminsix/', admin.site.urls),
    path('',views.index,name="index"),
    path('nosotros/',NosotrosView.as_view(),name="nosotros"),
   
    path('contactanos/',contactanosView,name="contactanos"),

    path('usuarios/', include('apps.usuarios.urls')),

    path("usuarios/", include("django.contrib.auth.urls")),
    path('publicacion/', include('apps.publicacion.urls')),
    path('comentario/', include('apps.comentario.urls'))
]
# LEER LAS URL DE LAS IMAGENES
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#no tengo STATIC en las apps
#urlpatterns += staticfiles_urlpatterns()

apps/publicacion/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.html import format_html

from apps.usuarios.models import Usuario


# CATEGORIA --------------------------------------
class Categoria(models.Model):
   categoria = models.CharField(max_length=30, null=False, verbose_name="Categoria")

   def __str__(self):
      return self.categoria

# POSTEOS --------------------------------------
class Publicacion(models.Model):
   titulo_publicacion = models.CharField(max_length=50, null=False, verbose_name="Título", help_text="Título de la publicación.")
   publicacion = models.TextField(null=False, verbose_name="Texto",help_text="Texto de la publicación.")
   resumen = models.TextField(max_length=255, blank=True, null=True)
   imagen = models.ImageField(null=True, blank=True, 
                              default='../static/img_default/public_default.jpg', 
                              upload_to='publicaciones', 
                              verbose_name="Imagen")
   fecha_publicacion = models.DateTimeField(auto_now=True, verbose_name="Publicado")
   fecha_modificacion = models.DateTimeField(default=timezone.now , verbose_name="Modificado")
   usuario = models.ForeignKey(Usuario, on_delete=models.PROTECT, null = True, verbose_name="Usuario")
   categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, default=0, verbose_name="Categoría")

   class Meta:
      ordering = ('titulo_publicacion',)

   def __str__(self):
      return self.titulo_publicacion
   
   def mostrar_imagen(self):
      return format_html('<img src="{}" width="100" />', format(self.imagen.url))

   def delete(self, using = None, keep_parents= False):
      self.imagen.delete(self.imagen.name)
      super().delete()


# COMENTARIOS --------------------------------------
""" class Comentario(models.Model):
   #antes
   comentario = models.TextField(max_length=150, null=False, verbose_name="Comentario")
   editado= models.BooleanField(default=False, verbose_name="Editado")
   fecha_comentario = models.DateTimeField(auto_now=True, verbose_name="Comentado el")
   fecha_modificacion = models.DateTimeField(default=timezone.now, verbose_name="Modificado")
   usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null = True, verbose_name="Usuario")
   publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, null = True, verbose_name= "Publicación") 

   #ahora
   publicacion = models.ForeignKey(Publicacion, related_name='comentarios_publicacion', on_delete=models.CASCADE)
   autor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comentarios_autor_publicacion', on_delete=models.CASCADE)
   texto = models.TextField()
   fecha_creacion = models.DateTimeField(default=timezone.now)

   def __str__(self):
      return f'{self.autor} comento en {self.publicacion} lo siguiente: {self.texo}' """
      # return self.comentario

apps/publicacion/forms.py
from .models import Categoria, Publicacion
from django import forms


class PublicacionForm(forms.ModelForm):
    nueva_categoria = forms.CharField(required=False, label="Nueva Categoría")

    class Meta:
        model = Publicacion
        fields = ['titulo_publicacion', 'publicacion', 'categoria', 'imagen']

    def __init__(self, *args, **kwargs):
        super(PublicacionForm, self).__init__(*args, **kwargs)
        self.fields['titulo_publicacion'].widget.attrs.update({'class': 'form-control'})
        self.fields['publicacion'].widget.attrs.update({'class': 'form-control'})
        self.fields['imagen'].widget = forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        self.fields['categoria'].widget.attrs.update({'class': 'form-control'})
        self.fields['nueva_categoria'].widget.attrs.update({'class': 'form-control'})


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['categoria']

    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Nombre de la categoría'})

apps/publicacion/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_list_or_404

from apps.comentario.forms import ComentarioForm
from .models import Publicacion, Categoria
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import CategoriaForm, PublicacionForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils import timezone

# Create your views here.

# Clase de crear categorias

class CrearPublicacionView(UserPassesTestMixin, CreateView):
    model = Publicacion
    form_class = PublicacionForm
    template_name = 'crear_publicacion.html'
    success_url = reverse_lazy('lista_publicaciones')

    # Este método asigna el autor al usuario logeado
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)


    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


# Clase para crear categorias

class CrearCategoriaView(UserPassesTestMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categorias/crear_categoria.html'

    def form_valid(self, form):
        form.save()
        return redirect('lista_publicaciones')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


# Clase para listar las publicaiones segun su categoria

class ListaPublicacionesPorCategoriaView(ListView):
    model = Publicacion
    template_name = 'lista_publicaciones.html'
    context_object_name = 'publicaciones'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        return context

    def get_queryset(self):
        categoria_id = self.kwargs.get('categoria_id')
        if categoria_id:
            return Publicacion.objects.filter(categoria_id=categoria_id)
        return Publicacion.objects.all()

# Clase para listar las publicaciones

class ListaPublicacionesView(ListView):
    model = Publicacion
    template_name = 'lista_publicaciones.html'
    context_object_name = 'publicaciones'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all() 
        return context
    
    def get_queryset(self):
        queryset = Publicacion.objects.all()
        orden = self.request.GET.get('orden')

        # Validación de los valores de 'orden'
        if orden not in ['antiguas', 'alfabetico', 'recientes']:
            orden = 'recientes'

        if orden == 'antiguas':
            queryset = queryset.order_by('fecha_publicacion')
        elif orden == 'alfabetico':
            queryset = queryset.order_by('titulo_publicacion')
        else:
            queryset = queryset.order_by('-fecha_publicacion')
        
        return queryset


# Clase para mostrar todo el contenido del post

class DetallePublicacionView(DetailView):
    model = Publicacion
    template_name = 'publicacion/detalle_publicacion.html'
    context_object_name = 'publicacion'

    def post(self, request, *args, **kwargs):
        object = self.get_object()
        form = ComentarioForm(request.POST)
        
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.publicacion = object
            comentario.autor = request.user
            comentario.fecha_creacion = timezone.now()
            comentario.fecha_modificacion  = timezone.now()

            comentario.save()
            return redirect('detalle_publicacion', pk=object.pk)
        return self.get_context_data(request, *args, **kwargs) 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ComentarioForm()
        return context
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
# Clase para Editar o modificar el post

class EditarPublicacionView(UserPassesTestMixin, UpdateView):
    model = Publicacion
    form_class = PublicacionForm
    template_name = 'publicacion/editar_publicacion.html'
    success_url = reverse_lazy('lista_publicaciones')
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


# Clase para borrar/eliminar el post

class BorrarPublicacionView(UserPassesTestMixin, DeleteView):
    model = Publicacion
    template_name = 'publicacion/eliminar_publicacion.html'
    success_url = reverse_lazy('lista_publicaciones')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

# Clase de lista de categoria

class ListaCategoriasView(UserPassesTestMixin, ListView):
    model = Categoria
    template_name = 'categorias/lista_categorias.html'
    context_object_name = 'categorias'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

# Clase de editar categoria

class EditarCategoriaView(UserPassesTestMixin, UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categorias/editar_categoria.html'
    success_url = reverse_lazy('lista_categorias')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
#Para eliminar/borrar la categoria

class EliminarCategoriaView(UserPassesTestMixin, DeleteView):
    model = Categoria
    template_name = 'categorias/eliminar_categoria.html'
    success_url = reverse_lazy('lista_categorias')

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
    

apps/publicacion/templates/publicacion/detalle_publicacion.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} BLOG {% endblock title %}

<!-- ==================================== -->


{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="post-title">{{ publicacion.titulo_publicacion }}</h1>

            <p class="post-meta">
                Publicado el: {{ publicacion.fecha_publicacion|date:"d/m/Y" }} | 
                Categoría: <span class="badge badge-info">{{ publicacion.categoria }}</span> | 
                Autor: <strong>{{ publicacion.usuario }}</strong>
            </p>
            
            {% if publicacion.imagen %}
                <img src="{{ publicacion.imagen.url }}" alt="{{ publicacion.titulo_publicacion }}" class="post-image img-fluid">
            {% endif %}
            
            <div class="post-content my-4">
                <p>{{ publicacion.publicacion }}</p>
            </div>

            <div class="btn-group mb-4">
                {% if request.user.is_superuser or request.user.is_staff %}
                    <a href="{% url 'editar_publicacion' publicacion.pk %}" class="btn" style="background-color: #6c757d; color: white; margin: 0 10px;">Editar</a>
                    <a href="{% url 'eliminar_publicacion' publicacion.pk %}" class="btn" style="background-color: #6c757d; color: white; margin: 0 10px;">Eliminar</a>
                {% endif %}
                <a href="{% url 'lista_publicaciones' %}" class="btn btn-secondary" style="margin: 0 10px;">Volver a la lista</a>
            </div>
            <!-- Comentarios existentes -->
            <h2>Comentarios</h2>
            <div class="list-group">
                {% for comentario in publicacion.comentarios_comentario.all %}
                    <div class="list-group-item">
                        <p><strong>{{ comentario.autor }}</strong>: {{ comentario.texto }}</p>
                        <p>Publicado el: {{ comentario.fecha_creacion }}</p>
                        {% if comentario.autor == user %}
                            <a href="{% url 'comentario:editar_comentario' pk=comentario.pk %}" class="btn btn-secondary btn-sm">Editar</a>
                            <a href="{% url 'comentario:eliminar_comentario' pk=comentario.pk %}" class="btn btn-danger btn-sm">Eliminar</a>
                        {% endif %}
                    </div>
                {% empty %}
                    <div class="alert alert-info">No hay comentarios aún. ¡Sé el primero en comentar!</div>
                {% endfor %}
            </div>
            
            <hr>

            <!-- Formulario para añadir un comentario -->
            <h2>Añadir un comentario:</h2>
            <form method="POST" action="{% url 'detalle_publicacion' publicacion.pk %}" class="form-group">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-2" style="background-color: #28a745; color: white; padding: 10px 20px; border-radius: 5px; text-transform: uppercase; text-decoration: none;">Comentar</button>
            </form>
        </div>
    </div>
</div>
{% endblock contenido %}

apps/publicacion/templates/publicacion/editar_publicacion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Publicación</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 50px;
        }
        .form-container {
            background-color: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }
        .btn-custom {
            background-color: rgb(4, 2, 78);
            border: none;
            color: white;
        }
        .btn-custom:hover {
            background-color: rgb(3, 2, 67);
        }
        .btn-secondary {
            background-color: #6c757d;
            border: none;
        }
        .btn-secondary:hover {
            background-color: #5a6268;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2 form-container">
                <h1>Editar Publicación</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="titulo_publicacion">Título de la Publicación</label>
                        {{ form.titulo_publicacion }}
                    </div>

                    <div class="form-group">
                        <label for="publicacion">Contenido</label>
                        {{ form.publicacion }}
                    </div>

                    <div class="form-group">
                        <label for="categoria">Categoría</label>
                        {{ form.categoria }}
                    </div>

                    <div class="form-group">
                        <label for="imagen">Imagen</label>
                        {{ form.imagen }}
                    </div>

                    <div class="btn-group mt-4" style="display: flex; justify-content: center;">
                        <button type="submit" class="btn btn-custom">Guardar Cambios</button>
                        <a href="{% url 'detalle_publicacion' publicacion.pk %}" class="btn btn-secondary ml-2">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

apps/publicacion/templates/publicacion/eliminar_publicacion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<div class="container mt-5">
    <h1>¿Estás seguro de que deseas eliminar esta publicación?</h1>
    <p><strong>{{ publicacion.titulo_publicacion }}</strong></p>
    <p>{{ publicacion.publicacion|slice:":150" }}...</p>

    <form method="post">
        {% csrf_token %}
        <a href="{% url 'detalle_publicacion' publicacion.pk %}" class="btn btn-secondary">Cancelar</a>
        <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

apps/publicacion/templates/publicacion/filtro_categorias.html
<div class="btn-group mb-4">
    <a href="{% url 'lista_publicaciones' %}" class="btn" style="background-color: #000f61; color: white; margin-right: 10px;">Todos</a>
    {% for categoria in categorias %}
        <a href="{% url 'lista_publicaciones_categoria' categoria.id %}" class="btn" style="background-color: #000f61; color: white; border: 1px solid #000f61; margin-right: 10px;">
            {{ categoria.categoria }}
        </a>
    {% endfor %}
</div>