apps/usuarios/urls.py
from django.urls import path, reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from .views import RegistrarUsuarioView, LoginUsuarioView,LogoutUsuarioView
from .views import PreLogoutUsuarioView, EditarUsuarioView

app_name='usuarios'

urlpatterns  = [
        path('registrar/',RegistrarUsuarioView.as_view(), name="registrar"),
        path('login/',LoginUsuarioView.as_view(), name="login"),
        path('prelogout/',login_required(PreLogoutUsuarioView.as_view()), name="prelogout"),
        path('logout/',login_required(LogoutUsuarioView.as_view()), name="logout"),
        path('editar/',EditarUsuarioView, name="editar"),
        
        path('password/change/', 
        auth_views.PasswordChangeView.as_view(template_name='password_change_form.html'), 
        name='password_change'),
        
        path('password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), 
            name='password_change_done'),
        
        path('password/reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html',
                        email_template_name = "password_reset_email.html",
                        success_url = reverse_lazy("usuarios:password_reset_done"),
                        subject_template_name = "password_reset_subject.txt"), 
                        name='password_reset'),
        
        path('password_reset/done/', 
                auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
                name='password_reset_done'),
        
        path('password/reset/<uidb64>/<token>/', 
                auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',
                                                            success_url = reverse_lazy("usuarios:password_reset_complete")), 
                name='password_reset_confirm'),
        
        path('password/reset/complete/', 
                auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
                name='password_reset_complete'),
        ]

proyBlog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import NosotrosView
from .viewsC import contactanosView
from . import views

urlpatterns = [
    path('adminsix/', admin.site.urls),
    path('',views.index,name="index"),
    path('nosotros/',NosotrosView.as_view(),name="nosotros"),
   
    path('contactanos/',contactanosView,name="contactanos"),

    path('usuarios/', include('apps.usuarios.urls')),

    path("usuarios/", include("django.contrib.auth.urls")),
    path('publicacion/', include('apps.publicacion.urls')),
    path('comentario/', include('apps.comentario.urls'))
]
# LEER LAS URL DE LAS IMAGENES
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#no tengo STATIC en las apps
#urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">
	<head>
		<!-- basic -->
		<meta charset="utf-8" />
		<!-- De esta forma indicas a los rastreadores que no muestren la versión almacenada en la caché en los resultados de búsqueda, sino la actual.-->
		<meta name="robots" content="noarchive" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<!-- mobile metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1" />
		<!-- site metas -->

		<title>{% block title %} INICIO {% endblock title %}</title>

		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<meta name="author" content="" />
		<!-- bootstrap css -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
		<!-- style css -->
		<link rel="stylesheet" href="{%  static 'css/style.css' %}" />
		<!-- Responsive-->
		<link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
		<!-- fevicon -->
		<link
			rel="icon"
			href="{% static 'images/fevicon.png' %}"
			type="image/gif"
		/>
		<!-- Scrollbar Custom CSS -->
		<link
			rel="stylesheet"
			href="{% static 'css/jquery.mCustomScrollbar.min.css' %}"
		/>
		<!-- Tweaks for older IEs-->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
		><![endif]-->
	</head>

	<body>
		<!-- loader  -->
		<div class="loader_bg">
			<div class="loader">
				<img src="{% static 'images/loading.gif' %}" alt="" />
			</div>
		</div>
		<!-- end loader -->

		<!-- ==================================== -->
		<!-- header -->
		<header>
			<!-- header inner -->
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-3 logo_section">
						<div class="full">
							<div class="center-desk">
								<div class="logo">
									<a href="{% url 'index' %}"
										><img
											src="{% static 'images/logo.png' %}"
											alt="Foto de Perfil"
									/></a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						<div class="menu-area">
							<div class="limit-box menu-area-texto">
								<nav class="main-menu">
									<ul class="menu-area-main">
										<li class="active">
											<a href="{% url 'index' %}">Inicio</a>
										</li>
										<li>
											
											<a href="{% url 'lista_publicaciones' %}">Blog</a>
										</li>
										<li>
											<a href="{% url 'nosotros' %}">Nosotros</a>
										</li>
										<li>
											<a href="{% url 'contactanos' %}">Contáctanos</a>
										</li>
							
										{% if user.is_authenticated %}
										<li>
											<a href="#">{{ user.username.upper }}</a>
											<ul>
												<li>
													<a href="{% url 'usuarios:editar' %}">Mi Perfil</a>
												</li>
												<li>
													<a href="{% url 'usuarios:prelogout' %}"
														>Cerrar Sesión</a
													>
												</li>
											</ul>
										</li>

										{% else %}

										<li>
											<a href="#">Usuarios</a>
											<ul>
												<li>
													<a href="{% url 'usuarios:login' %}"
														>Iniciar Sesión</a
													>
												</li>
												<li>
													<a href="{% url 'usuarios:registrar' %}">Registrar</a>
												</li>
											</ul>
										</li>
										{% endif %}
									</ul>
								</nav>
								{% if user.is_authenticated %}
								<div class="cont-foto-perfil">
									<img src="{{ user.foto.url }}" alt="" class="foto-perfil" />
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- end header inner -->
		</header>
		<!-- end header -->

		<!-- ==================================== -->

		{% block contenido %} {% endblock contenido %}

		<!-- ==================================== -->
		<!-- footer -->
		<footer>
			<div class="container">
				<div class="row">
					<div class="col-lg-4 col-md-6">
						<a href="#"
							><img src="{% static 'images/footer_logo.png' %}" alt="#"
						/></a>
						<ul class="contact_information">
							<li>
								<span
									><img
										src="{% static 'images/location_icon.png' %}"
										alt="#" /></span
								><span class="text_cont"
									>Informatorio 2024<br />Prov. Chaco</span
								>
							</li>
							<li>
								<span
									><img
										src="{% static 'images/phone_icon.png' %}"
										alt="#" /></span
								><span class="text_cont">987 654 3210</span>
							</li>
							<li>
								<span
									><img
										src="{% static 'images/mail_icon.png' %}"
										alt="#" /></span
								><span class="text_cont">demo@gmail.com</span>
							</li>
						</ul>
						<ul class="social_icon">
							<li>
								<a href="#"><i class="fa fa-facebook"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-twitter"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-linkedin"></i></a>
							</li>
							<li>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</li>
						</ul>
					</div>
					<div class="col-lg-2 col-md-6">
						<div class="footer_links">
							<h3>Menú</h3>
							<ul>
								<li>
									<a href="{% url 'index' %}"
										><i class="fa fa-angle-right" aria-hidden="true"></i>
										Inicio</a
									>
								</li>
								<li>
									<a href="{% url 'lista_publicaciones' %}"
										><i class="fa fa-angle-right" aria-hidden="true"></i>
										Blog</a
									>
								</li>
								<li>
									<a href="{% url 'nosotros' %}"
										><i class="fa fa-angle-right" aria-hidden="true"></i>
										Nosotros</a
									>
								</li>

								<li>
									<a href="{% url 'contactanos' %}"
										><i class="fa fa-angle-right" aria-hidden="true"></i>
										Contáctanos</a
									>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-lg-3 col-md-6">
						<div class="footer_links">
							<h3>Instagram</h3>
							<ol>
								<li>
									<img
										class="img-responsive"
										src="{% static 'images/footer_blog.png' %}"
										alt="#"
									/>
								</li>
								<!-- mas fotos -->
							</ol>
						</div>
					</div>
					
				</div>
			</div>
		</footer>
		<div class="cpy">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p>
							DERECHOS RESERVADOS © 2024 Design by
							<a href="https://html.design/">Free Html Templates</a>
						</p>
					</div>
				</div>
			</div>
		</div>
		<!-- end footer -->
		<!-- Javascript files-->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/popper.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
		<script src="{% static 'js/plugin.js' %}"></script>
		<!-- Scrollbar Js Files -->
		<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
	</body>
</html>

templates/contactanos.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} CONTÁCTANOS {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>CONTÁCTANOS</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<!-- ERRORES  -->
					{% if error != None %}
					<p>error: {{ error }}</p>
					{% endif %}
					<br />
					<div class="text_center">
						<small>
							{% if form.errors %}
							<hr />
							<h1>Errores</h1>
							<!---->
							{% for field in form %}

							<!---->
							{% if field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
						</small>
					</div>

					<!-- FORMULARIO  -->
					<h3>Completar los siguiente campos:</h3>
					<form
						method="POST"
						
						style="margin-top: 20px; margin-bottom: 50px"
					>
						{% csrf_token %}
						<div class="form-group">
							<label>Su nombre</label>
							{{ form.nombre }}
						</div>
						<div class="form-group">
							<label>Su correo</label>
							{{ form.correo }}
						</div>
						<div class="form-group">
							<label>El asunto</label>
							{{ form.asunto}}
						</div>

						<div class="form-group">
							<label>Su mensaje</label>
							{{ form.mensaje }}
						</div>

						<button type="submit" class="btn btn-custom hover-btn">
							ENVIAR
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end section -->
{% endblock contenido %}

templates/contactanosemail.html
ASUNTO: {{ asunto}}
------ 
MENSAJE: {{ mensaje }} 
------ 
USUARIO: {{ nombre }}
CORREO: {{ correo }}

templates/contactanosgracias.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %}  CONTÁCTANOS {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Gracias</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-12 text-center py-5">
			<h1 class="my-5 py-5">Su mensaje fue enviado. Pronto nos comunicaremos contigo.</h1>
		</div>
	</div>
</div>
{% endblock contenido %}

templates/index.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} INICIO {% endblock title %}

<!-- ==================================== -->
{% block contenido %}
<main>
	<!-- revolution slider -->
	<div class="banner-slider">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-7">
					<div id="slider_main" class="carousel slide" data-ride="carousel">
						<!-- The slideshow -->
						<div class="carousel-inner">
							<div class="carousel-item active">
								<img src="{% static 'images/slider_1.png' %}" alt="#" />
							</div>
							<div class="carousel-item">
								<img src="{% static 'images/slider_2.png' %}" alt="#" />
							</div>
							<div class="carousel-item">
								<img src="{% static 'images/slider_3.png' %}" alt="#" />
							</div>
						</div>
						<!-- Left and right controls -->
						<a
							class="carousel-control-prev"
							href="#slider_main"
							data-slide="prev"
						>
							<i class="fa fa-angle-left" aria-hidden="true"></i>
						</a>
						<a
							class="carousel-control-next"
							href="#slider_main"
							data-slide="next"
						>
							<i class="fa fa-angle-right" aria-hidden="true"></i>
						</a>
					</div>
				</div>
				<div class="col-md-5">
					<div class="full slider_cont_section">
						<h3>Six Blog</h3>
						<h4>Noticias actualizadas de IOT</h4>

						<p>
							El término IoT, o Internet de las cosas, se refiere a la red
							colectiva de dispositivos conectados, y a la tecnología que
							facilita la comunicación entre los dispositivos y la nube, así
							como entre los propios dispositivos. <br />
							Dispositivos de uso diario, como los cepillos de dientes, las
							aspiradoras, los coches y las máquinas, pueden utilizar sensores
							para recopilar datos y responder de forma inteligente a los
							usuarios.
						</p>
						<div class="button_section">
							<a href="{% url 'nosotros' %}">Nosotros</a>
							<a href="{% url 'contactanos' %}">Contáctanos</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end revolution slider -->

	<!-- section NOSOTROS -->
	<div class="section layout_padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="heading">
						<h3>Nosotros <span class="orange_color">Nosotros</span></h3>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<img src="{% static 'images/blog1.png' %}" alt="#" />
				</div>
				<div class="col-md-6">
					<div class="full blog_cont">
						<h4>Six Blog</h4>
						<h5>Informatorio 2024</h5>
						<p>
							Somos un grupo de estudiantes, más específicamente el GRUPO 6 de
							la Comisón 6 del Informatorio. <br />
							Desarrollamos este Blog, como proyecto final de la 2da etapa de
							capacitación del Informatorio.
						</p>
					</div> 
				</div>
			</div>

			<div class="row margin_top_30">
				<div class="col-md-12">
					<div class="button_section full center margin_top_30">
						<a style="margin: 0" href="{% url 'nosotros' %}">Nosotros</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end section -->
</main>
{% endblock contenido %}

templates/nosotros.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} NOSOTROS {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<!-- section -->
	<div class="About-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="aboutheading">
						<h3>Nosotros <span class="orange_color"> nosotros</span></h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="section layout_padding">
		<div class="container">
			<div class="row shadow p-3 mb-5 bg-body-tertiary rounded">
				<div class="col-md-6">
					<img src="{% static 'images/blog1.png' %}" alt="#" />
				</div>
				<div class="col-md-6">
					<div class="full blog_cont">
						<h4>Six Blog</h4>
						<h5>Informatorio 2024</h5>
						<p>
							Somos un grupo de estudiantes, más específicamente el GRUPO 6 de
							la Comisón 6 del Informatorio. <br />
							Desarrollamos este Blog, como proyecto final de la 2da etapa de
							capacitación del Informatorio.
						</p>
					</div>
				</div>
			</div>

			<!-- Magui -->
			<div>
				<div
					class="d-flex align-items-center margin_top_30 shadow p-3 mb-5 bg-body-tertiary rounded"
				>
					<div class="col-2">
						<img
							src="{% static 'images/magui.png' %}"
							alt="#"
							style="width: 130px"
						/>
					</div>
					<div class="col-10">
						<div class="full blog_cont">
							<h4>Magdalena Brollo</h4>

							<h5>
								En la actualidad trabajo como profesora. Siempre que resulte
								posible realizo cursos relacionados a informática. De todos
								los temas de informática, lo que más me gusta es programación,
								por eso decidí cursar el Informatorio.
							</h5>
						</div>
					</div>
				</div>
			</div>
		<!--Sonia-->
			<div>
				<div
					class="d-flex align-items-center margin_top_30 shadow p-3 mb-5 bg-body-tertiary rounded"
				>
					<div class="col-2">
						<img
							src="{% static 'images/Sonia.jpg' %}"
							alt="#"
							style="width: 130px"
						/>
					</div>
					<div class="col-10">
						<div class="full blog_cont">
							<h4>Hernández Sonia</h4>

							<h5>
								Soy Profesora de una Escuela Técnica. Siempre realice cursos relacionados a la informática. 																Hace un año decidi comenzar a realizar cursos de programación en el lenguaje de Arduino. Todo lo que 
								aprendi en el informatorio fue algo nuevo para mi.
							</h5>
						</div>
					</div>
				</div>
			</div>
			<!--Sebastian-->
			<div>
				<div
					class="d-flex align-items-center margin_top_30 shadow p-3 mb-5 bg-body-tertiary rounded"
				>
					<div class="col-2">
						<img
							src="{% static 'images/Gato.jpg' %}"
							alt="#"
							style="width: 130px"
						/>
					</div>
					<div class="col-10">
						<div class="full blog_cont">
							<h4>Segovia Sebastián</h4>
							<h5>
								Soy un estudiante de un colegio técnico, tengo 17 años. Estoy cursando el 3 año del ciclo superior de la carrera de IPP.
								Yo ya había realizado otros cursos relacionados a la programación en C++. Esta es la primera vez que realizo
								este tipo de curso. En el informatorio aprendí a utilizar nuevas herramientas y lenguajes que no conocia.
							</h5>
						</div>
					</div>
				</div>
			</div>
			<!--Maxi-->
			<div>
				<div
					class="d-flex align-items-center margin_top_30 shadow p-3 mb-5 bg-body-tertiary rounded"
				>
					<div class="col-2">
						<img
							src="{% static 'images/maxi.png' %}"
							alt="#"
							style="width: 130px"
						/>
					</div>
					<div class="col-10">
						<div class="full blog_cont">
							<h4>Coscia Maximiliano</h4>

							<h5>
								Soy de profesión Bombero, Enfermero y Paramédico. Actualmente ejerzo como instructor de la Academia Nacional de Bomberos,
								además de dedicarme a la medicina prehospitalaria. Si bien la programación es algo La programación es algo nuevo para mí, 
								siempre trato de satisfacer mi curiosidad y las ganas de aprender, que a futuro me puede servir para abrir nuevas puertas.
							</h5>
						</div>
					</div>
				</div>
			</div>
			<!--    fin nosotros      -->
			
		</div>
	</div>
	<!-- end section -->
</div>

{% endblock contenido %}