apps/usuarios/urls.py
from django.urls import path, reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from .views import RegistrarUsuarioView, LoginUsuarioView,LogoutUsuarioView
from .views import PreLogoutUsuarioView, EditarUsuarioView

app_name='usuarios'

urlpatterns  = [
        path('registrar/',RegistrarUsuarioView.as_view(), name="registrar"),
        path('login/',LoginUsuarioView.as_view(), name="login"),
        path('prelogout/',login_required(PreLogoutUsuarioView.as_view()), name="prelogout"),
        path('logout/',login_required(LogoutUsuarioView.as_view()), name="logout"),
        path('editar/',EditarUsuarioView, name="editar"),
        
        path('password/change/', 
        auth_views.PasswordChangeView.as_view(template_name='password_change_form.html'), 
        name='password_change'),
        
        path('password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), 
            name='password_change_done'),
        
        path('password/reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html',
                        email_template_name = "password_reset_email.html",
                        success_url = reverse_lazy("usuarios:password_reset_done"),
                        subject_template_name = "password_reset_subject.txt"), 
                        name='password_reset'),
        
        path('password_reset/done/', 
                auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), 
                name='password_reset_done'),
        
        path('password/reset/<uidb64>/<token>/', 
                auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',
                                                            success_url = reverse_lazy("usuarios:password_reset_complete")), 
                name='password_reset_confirm'),
        
        path('password/reset/complete/', 
                auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), 
                name='password_reset_complete'),
        ]

proyBlog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import NosotrosView
from .viewsC import contactanosView
from . import views

urlpatterns = [
    path('adminsix/', admin.site.urls),
    path('',views.index,name="index"),
    path('nosotros/',NosotrosView.as_view(),name="nosotros"),
   
    path('contactanos/',contactanosView,name="contactanos"),

    path('usuarios/', include('apps.usuarios.urls')),

    path("usuarios/", include("django.contrib.auth.urls")),
    path('publicacion/', include('apps.publicacion.urls')),
    path('comentario/', include('apps.comentario.urls'))
]
# LEER LAS URL DE LAS IMAGENES
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#no tengo STATIC en las apps
#urlpatterns += staticfiles_urlpatterns()

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.html import format_html


# USUARIOS --------------------------------------
class Usuario(AbstractUser):
   fecha_nacimiento = models.DateField(null=True, verbose_name="Fecha Nacimiento" )
   foto = models.ImageField(null=True, blank=True,
                     default='../static/img_default/usu_default.png', 
                     upload_to='usuarios', 
                     verbose_name="Foto de Perfil" )

     
   REQUIRED_FIELDS = [ 'first_name', 'last_name', 'email' ] #pide too para el super user
   USERNAME_FIELD = 'username'                                 

   @property
   def apellidos(self):
      return self.last_name
   @property
   def nombres(self):
      return self.first_name
   
   @property
   def nombre_usuario(self):
      return self.username
   
   @property
   def correo(self):
      return self.email
   
   @property
   def contrasenia(self):
      return self.password

   def __str__(self):
      return self.last_name +", "+ self.first_name
    
   def delete(self, using = None, keep_parents= False): #borrado en admin
      if self.foto.name != '../static/img_default/usu_default.png':
         self.foto.delete(self.foto.name)
      super().delete()

   def get_absolute_url(self):
      return reverse('index')

   def mostrar_foto(self):   #para el admin dj
      return format_html('<img src="{}" width="100" />', format(self.foto.url))

""" 
username
first_name
last_name
email
password
groups
user_permissions
is_staff
is_active
is_superuser
last_login
date_joined 
"""

apps/usuarios/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm

from .models import Usuario

#-----------------------------------------------------
class RegitrarUsuarioForm(UserCreationForm):
   
   class Meta:
      model = Usuario 
      fields = [
            'first_name',
            'last_name',
            'email',
            'fecha_nacimiento',
            'foto', 
            'username', 
            'password1',
            'password2'
      ]
   def __init__(self, *args, **kwargs):
      super(RegitrarUsuarioForm, self).__init__(*args, **kwargs)

      self.fields['first_name'].widget.attrs['class'] = 'form-control'
      self.fields['first_name'].widget.attrs['placeholder'] = 'Nombres'

      self.fields['last_name'].widget.attrs['class'] = 'form-control'
      self.fields['last_name'].widget.attrs['placeholder'] = 'Apellidos'

      self.fields['email'].widget.attrs['class'] = 'form-control'
      self.fields['email'].widget.attrs['placeholder'] = 'Correo'

      self.fields['fecha_nacimiento'].widget.attrs['class'] = 'form-control'
      self.fields['fecha_nacimiento'].widget.attrs['placeholder'] = 'Fecha de nacimiento (Ej. 01/10/1998)'

      self.fields['foto'].widget.attrs['class'] = 'form-control'
      self.fields['foto'].widget.attrs['placeholder'] = 'Foto de Perfil'

      self.fields['username'].widget.attrs['class'] = 'form-control'
      self.fields['username'].widget.attrs['placeholder'] = 'Nombre de Usuario'

      self.fields['password1'].widget.attrs['class'] = 'form-control'
      self.fields['password1'].widget.attrs['placeholder'] = 'Ingrese contraseña'

      self.fields['password2'].widget.attrs['class'] = 'form-control'
      self.fields['password2'].widget.attrs['placeholder'] = 'Vuelva a ingresar contraseña'

#-----------------------------------------------------
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
      self.request = kwargs.pop('request', None)
      super(LoginForm,self).__init__(*args,**kwargs)
      self.fields["username"].widget.attrs.update({'class' : 'form-control','placeholder' : "Nombre de usuario", 'type' : 'text'})
      self.fields["password"].widget.attrs.update({'class' : 'form-control','placeholder' : "Contraseña", 'type' : 'text'})

#-----------------------------------------------------
class EditarUsuarioForm(forms.ModelForm):
   
   class Meta:
      model = Usuario 
      fields = [
            'first_name',
            'last_name',
            'email',
            'fecha_nacimiento',
            'foto' 
      ]
      exclude = ['username','password']

   def __init__(self, *args, **kwargs):
      super(EditarUsuarioForm, self).__init__(*args, **kwargs)

      self.fields['first_name'].widget.attrs['class'] = 'form-control'
      self.fields['first_name'].widget.attrs['placeholder'] = 'Nombres'

      self.fields['last_name'].widget.attrs['class'] = 'form-control'
      self.fields['last_name'].widget.attrs['placeholder'] = 'Apellidos'

      self.fields['email'].widget.attrs['class'] = 'form-control'
      self.fields['email'].widget.attrs['placeholder'] = 'Correo'

      self.fields['fecha_nacimiento'].widget.attrs['class'] = 'form-control'
      self.fields['fecha_nacimiento'].widget.attrs['placeholder'] = 'Fecha de nacimiento (Ej. 01/10/1998)'

      self.fields['foto'].widget.attrs['class'] = 'form-control'
      self.fields['foto'].widget.attrs['placeholder'] = 'Foto de Perfil'

apps/usuarios/views.py
from django.contrib import messages
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage

from .forms import RegitrarUsuarioForm, LoginForm, EditarUsuarioForm
from .models import Usuario
# Create your views here.

#----------------------------------------
class RegistrarUsuarioView(CreateView):
   template_name = "registrar.html"
   form_class = RegitrarUsuarioForm
   model = Usuario
   success_url = reverse_lazy("usuarios:login")

   def form_valid(self, form):
      messages.success(self.request, 'Registro exitoso. Ahora puede Iniciar Sesión.')
      usuario=form.save()
      login(self.request, usuario) 
      return redirect('usuarios:login')

@login_required
def EditarUsuarioView(request):
   usuBuscado = request.user.id
   usuario = Usuario.objects.get(id = usuBuscado)
   viejaFoto = usuario.foto.name
   viejaFotoP = usuario.foto

   if request.method == 'POST':
      form = EditarUsuarioForm(request.POST, request.FILES,instance = usuario)
      if form.is_valid():
         usuario.first_name = form.cleaned_data['first_name']
         usuario.last_name = form.cleaned_data['last_name']
         usuario.email = form.cleaned_data['email']
         usuario.fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
         usuario.foto = form.cleaned_data['foto']

      #si la nueva foto es distinta de la default   
      if usuario.foto.name != '../static/img_default/usu_default.png':
         img_default = '../static/img_default/usu_default.png'

         if viejaFoto != usuario.foto.name and viejaFoto != img_default:
            #eliminar img anterior, si es dist de la actual y dist de default
            default_storage.delete(viejaFotoP.path)

         usuario.save()
         return redirect('index')
   else:
      form = EditarUsuarioForm(instance = usuario)

   context = {
      'form': form,
   }
   return render(request, 'editarUsuario.html', context)


#----------------------------------------
class LoginUsuarioView(LoginView):
   template_name = "login.html"
   form_class = LoginForm
   model = Usuario
   redirect_authenticated_user =True
   
   def get_success_url(self):
      messages.success(self.request, 'Login exitoso.')
      return reverse('index')
   
#----------------------------------------
class PreLogoutUsuarioView(TemplateView):
   template_name ='preLogout.html'

#----------------------------------------  
class LogoutUsuarioView(LogoutView):
   template_name = "logout.html"
   model = Usuario
   def get_success_url(self):
      messages.success(self.request, 'Logout exitoso.')
      return reverse('usuarios:logout')
   
   

apps/usuarios/templates/editarUsuario.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} Editar Perfil {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Editar Perfil</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<div class="log-in-out">
						<h3 style="color: black">Hola {{ user.username.upper }}!</h3>
						<img
							src="{{user.foto.url}}"
							alt="Foto de Perfil"
							class="foto-perfil-2"
						/>
					</div>

					<!-- ERRORES  -->
					<div class="text_center">
						<small>
							{% if form.errors %}
							<h1>Errores</h1>
							<!---->
							{% for field in form %}

							<!---->
							{% if field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
							<hr />
						</small>
					</div>

					<p>
						Desea cambiar su contraseña, hacer clic aquí:
						<a href="{% url 'usuarios:password_change' %}"
							>Cambiar Contraseña</a
						>
					</p>
					<hr />

					<!-- FORMULARIO  -->
					<h3>Completar los siguiente campos:</h3>
					<form
						method="POST"
						enctype="multipart/form-data"
						style="margin-top: 20px; margin-bottom: 50px"
					>
						{% csrf_token %}

						<div class="form-group">
							<label>Nombres</label>
							{{ form.first_name }}
						</div>

						<div class="form-group">
							<label>Apellidos</label>
							{{ form.last_name }}
						</div>

						<div class="form-group">
							<label>Foto de Perfil</label>
							{{ form.foto }}
						</div>
						<div class="form-group">
							<label>Correo Electrónico</label>
							{{ form.email }}
						</div>
						<div class="form-group">
							<label>Fecha de nacimiento (Ejemplo: 01/10/1998)</label>
							{{ form.fecha_nacimiento}}
						</div>

						<button type="submit" class="btn btn-custom hover-btn">
							GUARDAR CAMBIOS
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/login.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} REGISTRAR {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Iniciar sesión</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<div class="text_center">
						<small>
							{% if form.errors %}
							<h1>Errores</h1>
							<!---->
							{% for field in form %}
							<!---->
							{% if field.errors %}
							<p class="texto-rojo">TAGGGG: {{ field.label_tag }}</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>

							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
						</small>
						<hr />
					</div>
					<!-- FORMULARIO  -->
					<h3>Completar los siguiente campos:</h3>
					<form
						method="POST"
						enctype="multipart/form-data"
						style="margin-top: 20px; margin-bottom: 50px"
					>
						{% csrf_token %}

						<div class="form-group">
							<label>Nombre de Usuario</label>
							{{ form.username }}
						</div>

						<div class="form-group">
							<label>Contraseña</label>
							{{ form.password }}
						</div>

						<button type="submit" class="btn btn-custom hover-btn">
							Iniciar sesión
						</button>
					</form>

					<div class="row">
						<div class="button_section" style="margin-bottom: 100px">
							<a href="{% url 'usuarios:registrar' %}">No tengo cuenta</a>
						</div>

						<div class="button_section" style="margin-bottom: 100px">
							<a href="{% url 'usuarios:registrar' %}">Reset Contraseña</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/logout.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} LOGOUT {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh;">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Cerrar sesión</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2 log-in-out"
					style="margin-bottom: 100px"
				>

					<h3>Usted ha cerrado sesión ¿Desea INICIAR SESIÓN?</h3>
					
					<div class="button_section" style="margin-bottom: 100px">
						<a href="{% url 'usuarios:login' %}">INICIAR SESIÓN</a>
						
					</div>
	
					
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/password_change_done.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} CAMBIAR CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-12 text-center py-5">
			<h1 class="my-5 py-5">Contraseña cambiada correctamente!</h1>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/password_change_form.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} CAMBIAR CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Cambiar contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<div class="log-in-out">
						<h3 style="color: black">Hola {{ user.username.upper }}!</h3>
						<img
							src="{{user.foto.url}}"
							alt="Foto de Perfil"
							class="foto-perfil-2"
						/>
					</div>
					<!-- ERRORES  -->
					<div class="text_center">
						<small>
							{% if form.errors %}
							<h1>Errores</h1>
							<!---->
							{% for field in form %}
							<!---->
							{% if field.errors %}
							<p class="texto-rojo">TAGGGG: {{ field.label_tag }}</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>

							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
						</small>
						<hr />
					</div>

					<!-- FORMULARIO  -->
					<h3>Completar los siguiente campos:</h3>

					<form
						method="POST"
						action=""
						style="margin-top: 20px; margin-bottom: 50px"
					>
						{% csrf_token %}
						<br />
						{{ form.as_p }}
						<span style="margin-bottom: 12px"></span>
						<button type="submit" class="btn btn-custom hover-btn">
							GUARDAR
						</button>
						<!-- <button type="submit" class="btn get-started-btn">Guardar</button> -->
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/password_reset_complete.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} NUEVA CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Nueva Contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-12 text-center py-5"
					style="display: flex; flex-direction: column; align-items: center"
				>
					<h1 class="my-5 py-5">Su contraseña se reestableció correctamente</h1>
					<div class="button_section" style="margin-bottom: 100px">
						<a href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock contenido %}

apps/usuarios/templates/password_reset_confirm.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} RESET CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Nueva Contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<div class="text_center">
						<small>
							{% if form.errors %}
							<h1>Errores</h1>
							<!---->
							{% for field in form %}

							<!---->
							{% if field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
							<hr />
						</small>
					</div>

					<!-- FORMULARIO  -->

					{% if validlink %}
					<h3>Completar los siguientes datos:</h3>

					<form method="POST" style="margin-top: 20px; margin-bottom: 50px">
						{% csrf_token %}
						<div class="form-group">
							<label>Nueva Contraseña:</label>
							{{ form.new_password1 }}
						</div>

						{{ form.new_password2.errors }}

						<div class="form-group">
							<label>Confirme contraseña:</label>
							{{ form.new_password2 }}
						</div>

						<button type="submit" class="btn btn-custom hover-btn">
							CAMBIAR CONTRASEÑA
						</button>
						<!-- <input type="submit" class="btn btn-custom hover-btn" value="Cambiar mi contraseña" /> -->
					</form>
					<div class="button_section" style="margin-bottom: 100px">
						<a href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
					</div>
					{% else %}
					<h1 class="text-center">
						Enlace invalido: Este enlace ya ha sido utilizado
					</h1>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

apps/usuarios/templates/password_reset_done.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} RESET CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div class="light_silver" style="height: 80vh">
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12 text-center py-5">
			<h1 class="my-5 py-5">
				Le enviamos un enlace para reestablecer la contraseña. <br> 
				Controle su correo.
			</h1>
		</div>
	</div>
</div>

{% endblock contenido %}

apps/usuarios/templates/password_reset_email.html
Solicitaste reestablecimiento de contraseña desde la App SIX BLOG.
Click en el siguiente link para crear una nueva contraseña.
 {% block reset_link %} 
 
 {{ protocol }}://{{ domain }}{% url 'usuarios:password_reset_confirm' uid token %}

 {% endblock %} 
 Tu nombre de usuario es: {{ user.get_username }}

apps/usuarios/templates/password_reset_form.html
{% extends 'base.html' %}
<!-- ==================================== -->
{% load static %}

<!-- ==================================== -->
{% block title %} RESET CONTRASEÑA {% endblock title %}

<!-- ==================================== -->
{% block contenido %}

<div>
	<div class="Blog-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="Blogheading">
						<h3>Reset contraseña</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- section -->
	<div class="section light_silver">
		<div class="container">
			<div class="row">
				<div
					class="col-xs-12 col-sm-6 col-md-8 offset-md-2"
					style="margin-bottom: 100px"
				>
					<!-- ERRORES  -->
					<div class="text_center">
						<small>
							{% if form.errors %}
							<h1>Errores</h1>
							<!---->
							{% for field in form %}
							<!---->
							{% if field.errors %}
							<p class="texto-rojo">TAGGGG: {{ field.label_tag }}</p>
							<!---->
							{% for error in field.errors %}
							<p class="texto-rojo" style="font-weight: bold">
								{{ field.label_tag }}
							</p>

							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endfor %}
							<!---->
							{% if form.non_field_errors %}
							<!---->
							{% for error in form.non_field_errors %}
							<p class="texto-rojo">{{ error|escape }}</p>
							{% endfor %}
							<!---->
							{% endif %}
							<!---->
							{% endif %}
						</small>
						<hr />
					</div>

					<!-- FORMULARIO  -->
					<h3>Completar los siguiente campos:</h3>

					<p>Enviaremos un enlace a su correo para recuperar la contraseña:</p>
					<form method="POST">
						<br />
						{% csrf_token %}
						<label for="id_email">Su correo:</label>
						{{ form.email }}
						<br /><br />
						<button type="submit" class="btn btn-custom hover-btn">
							ENVIAR
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}